import 'package:petfitproject/bloc_cubit/service.dart';
import 'package:petfitproject/pojoClass/CountriesResponse.dart';
import 'package:petfitproject/pojoClass/newsApi.dart';

class TodoRepositoryImpl implements TodoRepository {
  TodoService service = TodoService();

  @override
  Future<Autogenerated> fetchData() {
    return service.fetchData();
  }
}

abstract class TodoRepository {
  Future<Autogenerated> fetchData();
}
