import 'dart:convert';
import 'dart:async';

import 'package:http/http.dart' as http;
import 'package:petfitproject/EnvUrl/env.dart';

import 'package:petfitproject/pojoClass/newsApi.dart';

class TodoService {
  Future<Autogenerated> fetchData() async {
    http.Response response = await http.get(
        Uri.parse(EnvironmentConstant.Base_url),
        headers: {"Accept": "application/json"});
    if (response.statusCode == 200) {
      final jsonMap = json.decode(response.body);
      Autogenerated temp = Autogenerated.fromJson(jsonMap);
      return temp;
    } else {
      throw Exception('Failed to load todos');
    }
  }
}
